-- Adds map spots without replacing the assembly's map_spots.xml files.
function on_xml_read()
    RegisterScriptCallback("on_xml_read", function(xml_file_name, xml_obj)
        if xml_file_name == [[ui\map_spots.xml]]
        or xml_file_name == [[ui\map_spots_16.xml]]
        or xml_file_name == [[ui\map_spots_21.xml]] then
            xml_obj:insertFromXMLString([[#include "ui\map_spots_rvm_sorties.xml"]])
        end
    end)
end
